// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

// Code points of text displayed to humans (SPEC-v0 section 3.1 item 8), derived from
// the Unicode Character Database.
const (
	zeroWidthNonJoiner = 0x200C
	zeroWidthJoiner    = 0x200D
	maxCodePoint       = 0x10FFFF
)

// forbiddenCategories are the general categories that never appear in displayed text:
// control, format, line and paragraph separator, private use, surrogate.
var forbiddenCategories = map[string]bool{"Cc": true, "Cf": true, "Zl": true, "Zp": true, "Co": true, "Cs": true}

var ucdVersion = regexp.MustCompile(`^# [A-Za-z]+-([0-9]+\.[0-9]+\.[0-9]+)\.txt`)

type codepointFile struct {
	Description    string   `json:"description"`
	UnicodeVersion string   `json:"unicode_version"`
	Forbidden      [][2]int `json:"forbidden"`
	Joiners        []int    `json:"joiners"`
	WhiteSpace     [][2]int `json:"white_space"`
}

// runCodepoints prints data/forbidden-codepoints-v0.json for the UCD files in a
// directory: UnicodeData.txt, DerivedCoreProperties.txt and PropList.txt.
func runCodepoints(args []string, stdout io.Writer) error {
	if len(args) != 1 {
		return errors.New("usage: vectors codepoints <directory with the UCD files>")
	}
	set := make([]bool, maxCodePoint+1)
	if err := markCategories(filepath.Join(args[0], "UnicodeData.txt"), set); err != nil {
		return err
	}
	version, ignorable, err := readProperty(filepath.Join(args[0], "DerivedCoreProperties.txt"), "Default_Ignorable_Code_Point")
	if err != nil {
		return err
	}
	if version == "" {
		return errors.New("DerivedCoreProperties.txt: no version in the first line")
	}
	_, selectors, err := readProperty(filepath.Join(args[0], "PropList.txt"), "Variation_Selector")
	if err != nil {
		return err
	}
	_, whiteSpace, err := readProperty(filepath.Join(args[0], "PropList.txt"), "White_Space")
	if err != nil {
		return err
	}
	mark(set, ignorable, true)
	mark(set, selectors, false)
	set[zeroWidthNonJoiner], set[zeroWidthJoiner] = false, false

	enc := json.NewEncoder(stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(codepointFile{
		Description: "Code points of text displayed to humans, SPEC-v0.md section 3.1 item 8. Ranges are inclusive. " +
			"forbidden: general categories Cc, Cf, Zl, Zp, Co, Cs and Default_Ignorable_Code_Point, without " +
			"Variation_Selector and the joiners. joiners: permitted only between two other code points. " +
			"white_space: not permitted as the first or last code point. " +
			"Generated by tools/vectors from the Unicode Character Database; do not edit.",
		UnicodeVersion: version,
		Forbidden:      ranges(set),
		Joiners:        []int{zeroWidthNonJoiner, zeroWidthJoiner},
		WhiteSpace:     merge(whiteSpace),
	})
}

// markCategories reads UnicodeData.txt and marks the code points of the forbidden
// categories, including the ranges given as a First/Last pair.
func markCategories(path string, set []bool) error {
	rangeStart := -1
	err := eachLine(path, func(line string) error {
		fields := strings.Split(line, ";")
		if len(fields) < 3 {
			return fmt.Errorf("too few fields: %q", line)
		}
		cp, err := parseCodePoint(fields[0])
		if err != nil {
			return err
		}
		first := cp
		switch {
		case strings.HasSuffix(fields[1], ", First>"):
			rangeStart = cp
			return nil
		case strings.HasSuffix(fields[1], ", Last>"):
			if rangeStart < 0 {
				return fmt.Errorf("range end without start: %q", line)
			}
			first, rangeStart = rangeStart, -1
		case rangeStart >= 0:
			return fmt.Errorf("range start without end before %q", line)
		}
		if forbiddenCategories[fields[2]] {
			mark(set, [][2]int{{first, cp}}, true)
		}
		return nil
	})
	if err == nil && rangeStart >= 0 {
		err = fmt.Errorf("%s: range start without end", filepath.Base(path))
	}
	return err
}

// readProperty returns the version of a UCD property file and the ranges of one property.
func readProperty(path, property string) (version string, found [][2]int, err error) {
	err = eachLine(path, func(line string) error {
		if m := ucdVersion.FindStringSubmatch(line); m != nil && version == "" {
			version = m[1]
		}
		data, _, _ := strings.Cut(line, "#")
		if strings.TrimSpace(data) == "" {
			return nil
		}
		codes, name, ok := strings.Cut(data, ";")
		if !ok {
			return fmt.Errorf("no property: %q", line)
		}
		if strings.TrimSpace(name) != property {
			return nil
		}
		lowText, highText, isRange := strings.Cut(strings.TrimSpace(codes), "..")
		low, err := parseCodePoint(lowText)
		if err != nil {
			return err
		}
		high := low
		if isRange {
			if high, err = parseCodePoint(highText); err != nil {
				return err
			}
		}
		found = append(found, [2]int{low, high})
		return nil
	})
	return version, found, err
}

func eachLine(path string, fn func(string) error) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		if scanner.Text() == "" {
			continue
		}
		if err := fn(scanner.Text()); err != nil {
			return fmt.Errorf("%s: %w", filepath.Base(path), err)
		}
	}
	return scanner.Err()
}

func parseCodePoint(s string) (int, error) {
	cp, err := strconv.ParseUint(strings.TrimSpace(s), 16, 32)
	if err != nil || cp > maxCodePoint {
		return 0, fmt.Errorf("code point %q", s)
	}
	return int(cp), nil
}

func mark(set []bool, list [][2]int, value bool) {
	for _, r := range list {
		for cp := r[0]; cp <= r[1]; cp++ {
			set[cp] = value
		}
	}
}

// ranges returns the marked code points as sorted inclusive ranges.
func ranges(set []bool) [][2]int {
	out := [][2]int{}
	for cp := 0; cp < len(set); cp++ {
		if !set[cp] {
			continue
		}
		start := cp
		for cp+1 < len(set) && set[cp+1] {
			cp++
		}
		out = append(out, [2]int{start, cp})
	}
	return out
}

// merge sorts ranges and joins adjacent ones.
func merge(list [][2]int) [][2]int {
	set := make([]bool, maxCodePoint+1)
	mark(set, slices.Clone(list), true)
	return ranges(set)
}
